import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Fictional example data — adapted from the design prototype so the map
// isn't empty on first run. Marked isSampleData: true throughout; delete
// these from /admin once you have real clubs to replace them with.
const SAMPLE_CLUBS = [
  {
    name: "Harbourside RFC",
    category: "rugby",
    city: "Wellington",
    country: "New Zealand",
    latitude: -41.2865,
    longitude: 174.7762,
    description:
      "Coastal club fielding two senior sides and a strong women's team. Regularly hosts overseas players for a season, pairs them with a billet family, and can usually line up bar or coaching work at a partner school.",
    skillLevel: 2,
    housingHelp: true,
    jobHelp: true,
    ageRangeMin: 18,
    ageRangeMax: 24,
    costTier: "Moderate",
    costDetail: "~NZ$220-280/week for food & incidentals",
    carNeeded: false,
    carNote: "Walkable to ground; buses cover the rest",
    socialScene:
      "Tight squad that trains together 3x a week and socialises hard after — most overseas players say the team becomes their main friend group within a month.",
    typicalWeek: "Training Tue/Thu evenings, match Saturday, coaching shifts at the partner school most weekday mornings.",
    placementLength: "Typically one full season (Apr-Sep)",
    intakeTiming: "Rolling, best to arrive by March",
    languageNeeded: "English required, conversational is fine",
    visaNote: "Working Holiday Visa covers this comfortably",
    nearby: "Beaches, Cook Strait ferry to the South Island, Wellington's cafe scene",
    safetyNotes: "Very safe city, standard precautions",
    contactName: "Sam Okafor, Club Secretary",
    contactPhone: "+64 4 555 0182",
    contactEmail: "gapyear@harboursiderfc.example",
    verified: false,
    lastContactedAt: null,
  },
  {
    name: "Stellenbosch Vine & Vale RFC",
    category: "rugby",
    city: "Stellenbosch",
    country: "South Africa",
    latitude: -33.9346,
    longitude: 18.8601,
    description:
      "Competitive club side attached to the local university league. Looking for players comfortable at provincial club standard. Shared player housing near the ground; work-seeking is on you.",
    skillLevel: 3,
    housingHelp: true,
    jobHelp: false,
    ageRangeMin: 19,
    ageRangeMax: 25,
    costTier: "Low",
    costDetail: "~R2,800-3,600/week for food & incidentals",
    carNeeded: true,
    carNote: "Town is spread out; a car or scooter helps a lot",
    socialScene:
      "Big shared player house, very social, but standard is high and it's a competitive-first environment rather than a beginner's social club.",
    typicalWeek: "Training most evenings, gym sessions, match day Saturday.",
    placementLength: "One season (Mar-Aug) minimum",
    intakeTiming: "Fixed intake in February",
    languageNeeded: "English widely spoken; some Afrikaans in daily life",
    visaNote: "Requires a visitor's visa endorsed for sport — check timing carefully",
    nearby: "Winelands, Cape Town an hour away, Table Mountain",
    safetyNotes: "Generally safe; usual city-travel awareness advised",
    contactName: "Pieter van Wyk, Tours Coordinator",
    contactPhone: "+27 21 555 0447",
    contactEmail: "tours@vinevalerfc.example",
    verified: false,
    lastContactedAt: null,
  },
  {
    name: "Ponsonby Fringe Rugby Club",
    category: "rugby",
    city: "Auckland",
    country: "New Zealand",
    latitude: -36.8563,
    longitude: 174.7445,
    description:
      "Social-first club welcoming complete beginners into a development side. No housing support, but the club owner's landscaping business regularly takes on gap year labourers.",
    skillLevel: 1,
    housingHelp: false,
    jobHelp: true,
    ageRangeMin: 18,
    ageRangeMax: 23,
    costTier: "High",
    costDetail: "~NZ$300-380/week — Auckland is pricey",
    carNeeded: false,
    carNote: "Good public transport in the inner suburbs",
    socialScene: "Very beginner-friendly and social — this club exists as much for the post-match drinks as the rugby.",
    typicalWeek: "One training night, casual Saturday matches, landscaping work most weekdays.",
    placementLength: "Flexible, from a few weeks to a full season",
    intakeTiming: "Rolling year-round",
    languageNeeded: "English required",
    visaNote: "Working Holiday Visa recommended for the landscaping work",
    nearby: "City beaches, Waiheke Island ferry, big live music scene",
    safetyNotes: "Safe, standard city awareness",
    contactName: "Riki Manu, Club Captain",
    contactPhone: "+64 9 555 0311",
    contactEmail: "join@ponsonbyfringe.example",
    verified: false,
    lastContactedAt: null,
  },
  {
    name: "Llanberis Valley RFC",
    category: "rugby",
    city: "Llanberis",
    country: "Wales, UK",
    latitude: 53.1189,
    longitude: -4.1264,
    description:
      "Small valley club near Snowdonia that's hosted overseas gap-year players for a decade. Homestay with a club family, plus seasonal work guiding at a local outdoor centre.",
    skillLevel: 2,
    housingHelp: true,
    jobHelp: true,
    ageRangeMin: 18,
    ageRangeMax: 22,
    costTier: "Low",
    costDetail: "~£90-130/week, food included in homestay",
    carNeeded: false,
    carNote: "Small village, everything's walkable",
    socialScene:
      "Close-knit village club — you'll be recognised in the pub within a week. Quiet compared to a city club, in a good way.",
    typicalWeek: "Training twice weekly, Saturday matches, guiding shifts at the outdoor centre.",
    placementLength: "3-6 months typical",
    intakeTiming: "Best start is September for the full season",
    languageNeeded: "English required, some Welsh in the community",
    visaNote: "Youth Mobility Scheme visa if eligible",
    nearby: "Snowdon, hiking and climbing straight from the village",
    safetyNotes: "Very safe, remote and quiet",
    contactName: "Eira Hughes, Secretary",
    contactPhone: "+44 1286 555 023",
    contactEmail: "secretary@llanberisvalley.example",
    verified: false,
    lastContactedAt: null,
  },
  {
    name: "Buenos Aires Costa RC",
    category: "rugby",
    city: "Buenos Aires",
    country: "Argentina",
    latitude: -34.6037,
    longitude: -58.3816,
    description:
      "High-performance club used to hosting serious overseas players wanting a competitive Argentine season. No support with housing or work — bring your own plan.",
    skillLevel: 4,
    housingHelp: false,
    jobHelp: false,
    ageRangeMin: 20,
    ageRangeMax: 27,
    costTier: "Moderate",
    costDetail: "~US$180-240/week for food & incidentals",
    carNeeded: false,
    carNote: "Good metro and bus network",
    socialScene: "Serious rugby culture first, social second — you'll earn your place, and friendships come through performance and time.",
    typicalWeek: "Training most weekday evenings, gym, match Saturday.",
    placementLength: "One season minimum to be taken seriously",
    intakeTiming: "Season starts March",
    languageNeeded: "Spanish strongly recommended",
    visaNote: "Tourist visa for short stays; longer stays need proper paperwork",
    nearby: "Big city nightlife, day trips to the Tigre Delta",
    safetyNotes: "Use normal city caution, especially at night",
    contactName: "Martin Ibanez, International Liaison",
    contactPhone: "+54 11 5555 0199",
    contactEmail: "internacional@costarc.example",
    verified: false,
    lastContactedAt: null,
  },
  {
    name: "Whistler Ridge Farm Collective",
    category: "farm work",
    city: "Whistler",
    country: "Canada",
    latitude: 50.1163,
    longitude: -122.9574,
    description:
      "WWOOF-style organic farm taking on 3-6 month volunteers. On-site cabin housing and food included in exchange for morning farm work; free afternoons for skiing in season.",
    skillLevel: 1,
    housingHelp: true,
    jobHelp: true,
    ageRangeMin: 18,
    ageRangeMax: 30,
    costTier: "Low",
    costDetail: "Housing & food included, ~CA$60-90/week spending money",
    carNeeded: false,
    carNote: "On-site; shuttle into town",
    socialScene: "Small rotating group of volunteers, communal meals, genuinely tight-knit — this is the classic farm-family gap year experience.",
    typicalWeek: "Farm work mornings, free afternoons — skiing in winter, hiking in summer.",
    placementLength: "3-6 months",
    intakeTiming: "Rolling, year-round",
    languageNeeded: "English fine, no fluency required",
    visaNote: "Working Holiday Visa (IEC) required for Canada",
    nearby: "World-class skiing, alpine lakes, Vancouver 2hrs away",
    safetyNotes: "Very safe, remote and rural",
    contactName: "Dana Reyes, Volunteer Coordinator",
    contactPhone: "+1 604 555 0166",
    contactEmail: "volunteer@whistlerridge.example",
    verified: false,
    lastContactedAt: null,
  },
  {
    name: "Kandy Hill Coaching Academy",
    category: "teaching",
    city: "Kandy",
    country: "Sri Lanka",
    latitude: 7.2906,
    longitude: 80.6337,
    description:
      "English and sport coaching placement at a village school. Homestay housing arranged with a local family; modest weekly stipend for coaching hours.",
    skillLevel: 1,
    housingHelp: true,
    jobHelp: true,
    ageRangeMin: 18,
    ageRangeMax: 25,
    costTier: "Low",
    costDetail: "~US$40-60/week, homestay meals included",
    carNeeded: false,
    carNote: "Village is walkable, tuk-tuks for anything further",
    socialScene:
      "Homestay-centred, warm and family-oriented rather than party-social — expect to bond with the family and other volunteers, not a big nightlife scene.",
    typicalWeek: "Coaching/teaching weekday mornings, free afternoons, community events some weekends.",
    placementLength: "6-12 weeks typical, longer possible",
    intakeTiming: "Rolling, new starts most months",
    languageNeeded: "English needed for teaching; basic Sinhala helpful",
    visaNote: "Tourist visa usually sufficient for short volunteer stints",
    nearby: "Temple of the Tooth, tea plantations, hill country trains",
    safetyNotes: "Generally safe; standard travel precautions",
    contactName: "Nadeesha Perera, Programme Lead",
    contactPhone: "+94 81 555 0288",
    contactEmail: "volunteers@kandyhill.example",
    verified: false,
    lastContactedAt: null,
  },
  {
    name: "Queenstown Alpine Ski Crew",
    category: "ski season",
    city: "Queenstown",
    country: "New Zealand",
    latitude: -45.0312,
    longitude: 168.6626,
    description:
      "Lift operations and lodge work for the winter season. Staff accommodation on-site; ski pass included; some rugby-playing staff turn out for the local social side too.",
    skillLevel: 2,
    housingHelp: true,
    jobHelp: true,
    ageRangeMin: 18,
    ageRangeMax: 26,
    costTier: "Moderate",
    costDetail: "~NZ$180-250/week, accommodation covered",
    carNeeded: false,
    carNote: "Staff shuttle to the mountain",
    socialScene: "Big, loud seasonal-staff scene — shared lodges, constant apres-ski socialising, easy to make friends fast.",
    typicalWeek: "5-6 shifts a week on the mountain, days off used for riding or resting.",
    placementLength: "One winter season (Jun-Sep)",
    intakeTiming: "Fixed intake in May",
    languageNeeded: "English required",
    visaNote: "Working Holiday Visa required",
    nearby: "Skiing, bungy jumping, Milford Sound day trips",
    safetyNotes: "Safe; usual mountain-safety awareness",
    contactName: "Josh Fletcher, Staffing Manager",
    contactPhone: "+64 3 555 0421",
    contactEmail: "season@alpinecrew.example",
    verified: false,
    lastContactedAt: null,
  },
];

async function main() {
  const existing = await prisma.club.count();
  if (existing > 0) {
    console.log(`Database already has ${existing} club(s) — skipping seed.`);
    return;
  }

  for (const club of SAMPLE_CLUBS) {
    await prisma.club.create({ data: { ...club, isSampleData: true } });
  }

  console.log(`Seeded ${SAMPLE_CLUBS.length} sample clubs.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
